server:
  port: ${PORT:8080}

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

application:
  security:
    jwt:
      # A 256-bit base64 secret key for HMAC-SHA256
      secret-key: ${JWT_SECRET_KEY:}
      # 1 day expiration in ms (24 hours * 60 mins * 60 secs * 1000 ms)
      expiration: 86400000

nomba:
  api:
    url: ${NOMBA_API_URL:https://sandbox-api.nomba.com}
  client:
    id: ${NOMBA_CLIENT_ID:placeholder-id}
    secret: ${NOMBA_CLIENT_SECRET:placeholder-secret}
    account-id: ${NOMBA_ACCOUNT_ID:placeholder-account-id}

